[tool.poetry]
name = "llm-compiler-with-rag"
version = "0.1.0"
description = ""
authors = ["Manh Nguyen Dong"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
